### ISSUE TITLE
Activity failed to start...

### ISSUE THREAD

**Issue by samswag** [Thekiddiejsandpython/SecretMessage.activity#1]
I am currently running the latest version of Sugar on Fedora 27. Your activity is failing.
/usr/lib/python2.7/site-packages/sugar3/activity/activity.py:96: PyGIWarning: SugarExt was imported without specifying a version first. Use gi.require_version('SugarExt', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import SugarExt
Traceback (most recent call last):
  File "/usr/local/bin/sugar-activity", line 219, in <module>
    main()
  File "/usr/local/bin/sugar-activity", line 167, in main
    activity_constructor = getattr(module, class_name)
AttributeError: 'module' object has no attribute 'SecretMessage'
Exited with status 1, pid 9396 data (<open file '<fdopen>', mode 'w' at 0x7ff042133d20>, '2df5f51634f0732c955671fc4e81afe8fe18ec05')

Next thing you need to do is, you should save your folder as SecretMessage.activity.

Because the Sugar OS only registers activity/apps with .xo format and .activity on folder

**Comment by jorrell-templeton** [comment]
The necessary changes seem to have been made, so it should work now. Sorry about the issue :)
